name: Formatting and Linting

on:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  setup-build-lint:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y check clang-format clang-tidy cmake

      - name: Set up workspace
        run: |
          # Create workspace structure
          mkdir -p $HOME/ws/build $HOME/ws/install $HOME/ws/src

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: $HOME/ws/src

      - name: Set up build
        run: |
          # Extract package name from CMakeLists.txt project() definition
          PACKAGE_NAME=$(grep -m1 -Po 'project\(\K[^\)]+' $HOME/ws/src/CMakeLists.txt)
          echo "Detected package name: $PACKAGE_NAME"

          # Create build directory for the package
          mkdir -p $HOME/ws/build/$PACKAGE_NAME

          # Navigate to the package-specific build directory
          cd $HOME/ws/build/$PACKAGE_NAME

          # Configure with specified flags and set install prefix to $HOME/ws/install
          cmake ../../src \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DENABLE_TESTS=ON \
            -DCMAKE_INSTALL_PREFIX=$HOME/ws/install

          # Install to the specified install directory
          make install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit cmakelang[YAML]

      - name: Run pre-commit checks
        run: pre-commit run --all-files --files $HOME/ws/src
