name: ci_mkdocs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y doxygen cmake

      - name: Build API docs
        run: |
          mkdir build && cd build

          cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_DOC=ON

          cmake --build . --target docs

          mv docs/html ../docs/api_html

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
