name: ci_mkdocs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake graphviz flex bison

      - name: Install Doxygen from source
        run: |
          wget https://doxygen.nl/files/doxygen-1.12.0.src.tar.gz
          tar -xvzf doxygen-1.12.0.src.tar.gz
          cd doxygen-1.12.0
          mkdir build
          cd build
          cmake -G "Unix Makefiles" ..
          make -j $(nproc)
          sudo make install
          cd ../..
          # Clean up
          rm -rf doxygen-1.12.0
          rm doxygen-1.12.0.src.tar.gz

      - name: Build API docs
        run: |
          mkdir build && cd build

          cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_DOC=ON

          cmake --build . --target docs

          mv docs/api_html ../docs/api_html

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
